### ISSUE TITLE
java.lang.ClassNotFoundException: brave.kafka.interceptor.TracingProducerInterceptor

### ISSUE THREAD

**Issue by skalinets** [openzipkin-contrib/brave-kafka-interceptor#7]
[How to test section](https://github.com/openzipkin-contrib/brave-kafka-interceptor#how-to-test-it) doesn't seem to work. I executed all steps until Create Stream, when faced error "topic does not exist". After investigation I found errors with both sink and source.
 
Error for source: 

`curl http://localhost:8083/connectors/jdbc_source/status
{"name":"jdbc_source","connector":{"state":"RUNNING","worker_id":"localhost:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"localhost:8083","trace":"org.apache.k
afka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:433)\n\tat org.apache.ka
fka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:270)\n\tat org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:514)\n\tat org.apache.kafka
.connect.runtime.Worker.startTask(Worker.java:459)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1036)\n\tat or
g.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:117)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerd
er$13.call(DistributedHerder.java:1051)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1047)\n\tat java.util.concu
rrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolEx
ecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.common.KafkaException: brave.kafka.interceptor.
TracingProducerInterceptor ClassNotFoundException exception occurred\n\tat org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:425
)\n\tat org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:400)\n\tat org.apache.kafka.common.config.AbstractConfig.getConfigured
Instances(AbstractConfig.java:387)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:379)\n\t... 11 more\nCaused by: java.lang.ClassNotFo
undException: brave.kafka.interceptor.TracingProducerInterceptor\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:382)\n\tat java.lang.ClassLoader.loadClass
(ClassLoader.java:424)\n\tat org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)\n\tat java.lang.ClassLoader.loadClass(C
lassLoader.java:357)\n\tat java.lang.Class.forName0(Native Method)\n\tat java.lang.Class.forName(Class.java:348)\n\tat org.apache.kafka.common.utils.Utils.loadClass(Ut
ils.java:348)\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:337)\n\tat org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(Abstract
Config.java:423)\n\t... 14 more\n"}],"type":"source"}%`

git revision ee556bf

**Comment by jeqo** [comment]
Thanks @skalinets for reporting this. I've updated docs and scripts to improve this experience. Would you mind to take a look to #8 and check if it's working better now?

**Comment by skalinets** [comment]
I tried it, but it still don't work with the same error messages. Do it work for you? @jeqo

**Comment by jeqo** [comment]
@skalinets I realized I haven't add a not about building the project before starting containers. Added now. Try again please.

**Comment by skalinets** [comment]
@jeqo  yes, it works now! thanks
